import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextProvider } from "./providers";
import NextLayout from "@/components/NextLayout";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased h-screen`}>
        <div
          className="fixed left-0 right-0 bottom-0 mx-auto flex justify-center z-10"
          id="root-portal"
        ></div>
        <NextProvider>
          <NextLayout>{children}</NextLayout>
        </NextProvider>
      </body>
    </html>
  );
}
