import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { HeaderTransparent } from "@/components/shared/Header";
import { NextLayout } from "./providers";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased h-screen`}>
        <div
          className="w-[430px] fixed left-0 right-0 bottom-0 mx-auto flex justify-center z-10"
          id="root-portal"
        ></div>
        <NextLayout>{children}</NextLayout>
      </body>
    </html>
  );
}
